# Generated by Django 2.0.6 on 2018-06-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180625_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
