# Generated by Django 2.0.6 on 2018-06-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
