# Generated by Django 2.0.6 on 2018-06-25 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_question_upvotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='upvotes',
        ),
    ]
