# Generated by Django 2.0.6 on 2018-06-25 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_answer_upvotes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Votes',
            new_name='Vote',
        ),
    ]
