# Generated by Django 2.0.6 on 2018-06-26 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180625_1358'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vote',
            new_name='QuestionVote',
        ),
    ]
