# Generated by Django 2.0.6 on 2018-06-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_question_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tag',
            field=models.CharField(default='Something', max_length=20),
        ),
    ]
