# Generated by Django 2.0.6 on 2018-06-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_question_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.CharField(default=-1.0, max_length=20),
            preserve_default=False,
        ),
    ]
